import type { Metadata } from "next";
import { Geist, Geist_Mono, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { Poppins } from "next/font/google"
import Navbar from "@/components/Navbar";
import { cookies } from "next/headers";
import jwt from "jsonwebtoken"
import Container from "@/components/Container";
import { cn } from "@/lib/utils";
import Footer from "@/components/Footer";

const jetbrainsMono = JetBrains_Mono({subsets:['latin'],variable:'--font-mono'});

const poppins = Poppins({
  weight: ['400', '500', '600', '700'],
  subsets: ["latin"],
  variable: "--font-poppins"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;

}>) {
  const cookieStore = await cookies()
  const token = cookieStore.get('token')
  const jwtSecret = process.env.JWT_SECRET as string
  const decoded = token ? jwt.verify(token.value, jwtSecret) as {id:string, name:string, role:string} : null
  const isCompany = decoded ? decoded.role === "company"? true : false  : null
  const isLoggedIn = !!token
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={cn("h-full", "antialiased", poppins.variable, poppins.variable, "font-mono", jetbrainsMono.variable)}
    >
      <body className="min-h-full flex flex-col">
        <Navbar isLoggedIn={isLoggedIn} isCompany={isCompany as boolean}  />
        <Container>
        {children}
        </Container>
        <Footer />
        </body>
      
    </html>
  );
}
